stages:
  - build

variables:
  BUILD_PATH: "${CI_PROJECT_DIR}/forge/build"
  INSTALL_PATH: "${CI_PROJECT_DIR}/forge/install"

image: jeanbez/forge

compile FORGE:
  stage: build
  script:
    - mkdir -p ${BUILD_PATH} && cd ${BUILD_PATH}
    - cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PATH} ${CI_PROJECT_DIR}
    - make
  artifacts:
    paths:
     - ${INSTALL_PATH}
