stages:
  - build
  - test

variables:
  BUILD_PATH: "${CI_PROJECT_DIR}/forge/build"
  INSTALL_PATH: "${CI_PROJECT_DIR}/forge/install"
  LOG_PATH: "${CI_PROJECT_DIR}/logs"
  TESTS_PATH:  "${CI_PROJECT_DIR}/test"

image: jeanbez/forge

compile FORGE:
  stage: build
  script:
    - mkdir -p ${BUILD_PATH} && cd ${BUILD_PATH}
    - cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PATH} ${CI_PROJECT_DIR}
    - make
  artifacts:
    paths:
     - ${INSTALL_PATH}

test file-per-process:
  stage: test
  script:
    - mkdir -p "${LOG_PATH}"
    - mpirun -np 9 --oversubscribe ${INSTALL_PATH}/forge ${TESTS_PATH}/file-per-process.json ${CI_PROJECT_DIR}/logs/file-per-process.log
  artifacts:
    paths:
     - "${LOG_PATH}"

