stages:
  - build
  - test single
  - test multiple

variables:
  BUILD_PATH: "${CI_PROJECT_DIR}/forge/build"
  INSTALL_PATH: "${CI_PROJECT_DIR}/forge/install"
  LOG_PATH: "${CI_PROJECT_DIR}/logs"
  TESTS_PATH: "${CI_PROJECT_DIR}/test"
  TEMPORARY_PATH: "${CI_PROJECT_DIR}/tmp"

image: jeanbez/forge

compile FORGE:
  stage: build
  script:
    - mkdir -p ${BUILD_PATH} && cd ${BUILD_PATH}
    - cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PATH} ${CI_PROJECT_DIR}
    - make
    - make install
  artifacts:
    paths:
     - ${INSTALL_PATH}

one-forwarder file-per-process:
  stage: test single
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 9 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/one-forwarder/file-per-process.json ${LOG_PATH}
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/one-forwarder/file-per-process.json.map"
     - "${TESTS_PATH}/one-forwarder/file-per-process.json.time"

one-forwarder shared-file-contiguous:
  stage: test single
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 9 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/one-forwarder/shared-file-contiguous.json ${LOG_PATH}
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/one-forwarder/shared-file-contiguous.json.map"
     - "${TESTS_PATH}/one-forwarder/shared-file-contiguous.json.time"

one-forwarder shared-file-strided:
  stage: test single
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 9 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/one-forwarder/shared-file-strided.json ${LOG_PATH}
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/one-forwarder/shared-file-strided.json.map"
     - "${TESTS_PATH}/one-forwarder/shared-file-strided.json.time"

two-forwarders file-per-process:
  stage: test multiple
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 10 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/two-forwarders/file-per-process.json ${LOG_PATH}
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/two-forwarders/file-per-process.json.map"
     - "${TESTS_PATH}/two-forwarders/file-per-process.json.time"

two-forwarders shared-file-contiguous:
  stage: test multiple
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 10 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/two-forwarders/shared-file-contiguous.json ${LOG_PATH}
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/two-forwarders/shared-file-contiguous.json.map"
     - "${TESTS_PATH}/two-forwarders/shared-file-contiguous.json.time"

two-forwarders shared-file-strided:
  stage: test multiple
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 10 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/two-forwarders/shared-file-strided.json ${LOG_PATH}
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/two-forwarders/shared-file-strided.json.map"
     - "${TESTS_PATH}/two-forwarders/shared-file-strided.json.time"

four-forwarders file-per-process:
  stage: test multiple
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 12 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/four-forwarders/file-per-process.json ${LOG_PATH}
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/four-forwarders/file-per-process.json.map"
     - "${TESTS_PATH}/four-forwarders/file-per-process.json.time"

four-forwarders shared-file-contiguous:
  stage: test multiple
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 12 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/four-forwarders/shared-file-contiguous.json ${LOG_PATH}
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/four-forwarders/shared-file-contiguous.json.map"
     - "${TESTS_PATH}/four-forwarders/shared-file-contiguous.json.time"

four-forwarders shared-file-strided:
  stage: test multiple
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 12 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/four-forwarders/shared-file-strided.json ${LOG_PATH}
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/four-forwarders/shared-file-strided.json.map"
     - "${TESTS_PATH}/four-forwarders/shared-file-strided.json.time"


