stages:
  - build
  - test

variables:
  BUILD_PATH: "${CI_PROJECT_DIR}/forge/build"
  INSTALL_PATH: "${CI_PROJECT_DIR}/forge/install"
  LOG_PATH: "${CI_PROJECT_DIR}/logs"
  TESTS_PATH: "${CI_PROJECT_DIR}/test"
  TEMPORARY_PATH: "${CI_PROJECT_DIR}/tmp"

image: jeanbez/forge

compile FORGE:
  stage: build
  script:
    - mkdir -p ${BUILD_PATH} && cd ${BUILD_PATH}
    - cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PATH} ${CI_PROJECT_DIR}
    - make
    - make install
  artifacts:
    paths:
     - ${INSTALL_PATH}

test file-per-process:
  stage: test
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 9 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/file-per-process.json ${CI_PROJECT_DIR}/logs/file-per-process.log
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/file-per-process.json.map"
     - "${TESTS_PATH}/file-per-process.json.time"
     - "${TESTS_PATH}/file-per-process.json.0.stats"

test shared-file-contiguous:
  stage: test
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 9 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/shared-file-contiguous.json ${CI_PROJECT_DIR}/logs/shared-file-contiguous.log
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/shared-file-contiguous.json.map"
     - "${TESTS_PATH}/shared-file-contiguous.json.time"
     - "${TESTS_PATH}/shared-file-contiguous.json.0.stats"

test shared-file-strided:
  stage: test
  script:
    - mkdir -p "${LOG_PATH}"
    - mkdir -p "${TEMPORARY_PATH}"
    - cp agios/* /tmp/
    - cd "${TEMPORARY_PATH}"
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - mpirun --allow-run-as-root --oversubscribe --np 9 ${INSTALL_PATH}/bin/forge ${TESTS_PATH}/shared-file-strided.json ${CI_PROJECT_DIR}/logs/shared-file-strided.log
  artifacts:
    paths:
     - "${LOG_PATH}"
     - "${TESTS_PATH}/shared-file-strided.json.map"
     - "${TESTS_PATH}/shared-file-strided.json.time"
     - "${TESTS_PATH}/shared-file-strided.json.0.stats"

